---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: aws-to-k8s-labels
rules:
  - apiGroups: ["*"]
    resources: ["nodes"]
    verbs: ["get", "list", "patch"]
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: aws-to-k8s-labels
  namespace: kube-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: aws-to-k8s-labels
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: aws-to-k8s-labels
subjects:
- kind: ServiceAccount
  name: aws-to-k8s-labels
  namespace: kube-system
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: aws-to-k8s-labels
  namespace: kube-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app: aws-to-k8s-labels
  template:
    metadata:
      labels:
        app: aws-to-k8s-labels
    spec:
      nodeSelector:
        kubernetes.io/role: master
      tolerations:
      - effect: NoSchedule
        key: node-role.kubernetes.io/master
      serviceAccountName: aws-to-k8s-labels
      containers:
      - name: aws-to-k8s-labels
        image: onfido/aws-to-k8s-labels:latest
        imagePullPolicy: Always
        resources:
          limits:
            memory: 100Mi
            cpu: 50m
        env:
        - name: REGION
          value: eu-west-1
