apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: aws-to-k8s-labels
  namespace: kube-system
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: aws-to-k8s-labels
      annotations:
        scheduler.alpha.kubernetes.io/tolerations: |
          [
            {
              "key": "dedicated",
              "operator": "Equal",
              "value": "master",
              "effect": "NoSchedule"
            }
          ]
    spec:
      nodeSelector:
        kubernetes.io/role: master
      containers:
      - name: aws-to-k8s-labels
        image: onfido/aws-to-k8s-labels:latest
        imagePullPolicy: Always
        resources:
          limits:
            memory: 100Mi
            cpu: 50m
        env:
        - name: REGION
          value: eu-west-1
